### ISSUE TITLE
Test that solo can be run on windows

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/solo#129]
We haven't tested `solo` on windows. However, we should ensure it can be run on windows. If not, we need to create tickets to resolve those issues.
```[tasklist]
### Tasks
- [ ] Insall required package for solo, such as kind, helm, nodejs for windows environment
- [ ] Solo unit test for windows environment
- [ ] Solo end to end test for windows environment
- [ ] kindest/node support for windows
```

**Comment by leninmehedy** [comment]
Currently we mentioned that `solo` can be used on `darwin` and `linux`: https://github.com/hashgraph/solo/blob/main/package.json#L71

If it it can be run on windows, we may update that line in package.json.

**Comment by JeffreyDallas** [comment]
Summary of current experiments:

- kind/node and minikube does not support to run on windows
- Github runners currently only support WSL1 on windows
- Could not install nodejs with WSL1 ubuntu distribution, either get `cannot execute binary file: Exec format error` or `WSL 1 is not supported. Please upgrade to WSL 2 or above`
- Github large runners can support WSL2 if nested virtualization is enabled

**Comment by JeffreyDallas** [comment]
Tried with different machine types (N2, C3) on GKE,
once enabled nested virtualization.
https://raaki-88.medium.com/enabling-nested-virtualisation-on-google-cloud-platform-instance-7f80f3120834
no longer able to connect to remote instance with Microsoft Remote Desktop

```
advancedMachineFeatures:
  enableNestedVirtualization: true

```
