### ISSUE TITLE
Project Migration

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/solo#2]
## Description

The source code for the `Solo` application lives in the `hashgraph/full-stack-testing` repository, but needs to be migrated to this repository (`hashgraph/solo`). 

This is the epic issue which should be used to track the individual issues involved in migrating the code.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/solo/issues/3
- [ ] https://github.com/hashgraph/solo/issues/5
- [ ] https://github.com/hashgraph/solo/issues/4
- [ ] https://github.com/hashgraph/solo/issues/8
- [ ] https://github.com/hashgraph/solo/issues/26
- [ ] https://github.com/hashgraph/solo/issues/9
- [ ] https://github.com/hashgraph/solo/issues/29
```
