### ISSUE TITLE
Generate docs using CI pipeline

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/solo#39]
We would like to use Hugo for our docs site, see demo: https://geekdocs.de/
Here is the Hugo theme template: https://themes.gohugo.io/themes/hugo-geekdoc/
We also need to generate class docs using https://jsdoc.app/.

Documentation (class and CLI docs ) needs to be published using the Hugo theme as Github page. CI pipeline needs to be created so that the docs are generated and released regularly along with our release schedule.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/solo/issues/118
- [ ] https://github.com/hashgraph/solo/issues/119
- [ ] https://github.com/hashgraph/solo/issues/120
- [ ] https://github.com/hashgraph/solo/issues/121
```

**Comment by JeffreyDallas** [comment]
All subtasks have been closed
