### ISSUE TITLE
Inspect existing cluster resources during cluster setup

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/solo#42]
`solo` needs to check for existing operator setup/configuration before installing `cluster setup chart`. 

```[tasklist]
### Tasks
- [ ] scan all pods for all namespaces for a label of 'app:cert-manager', if none exists install cert-manager and install acme-cluster-issuer, if it does exist install acme-cluster-issuer
- [ ] detect if minio operator has been installed if not, then install it, unless flag is set to not install minio
- [ ] detect if ingress controller is installed, if not, install the haproxy ingress controller
- [x] don't remove minio during destroy/uninstall ( obsolete )
- [ ] before destroying/uninstalling solo cluster setup chart check if any namespace has a remote config, if so prompt the user with a warning and if they wish to continue
- [ ] if all of the required components are installed then solo cluster setup chart does not need to be installed and can exit successfully
```
- relates to https://github.com/hashgraph/solo-charts/issues/58
