### ISSUE TITLE
Ability to stand up and tear down an entire network in a single command/subcommand

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#519]
- [ ] depends on https://github.com/hashgraph/solo/issues/694

```[tasklist]
### Tasks
- [x] add a task 'solo:deploy' that will run init, node keys, cluster setup, network deploy with 3 nodes, node setup, and node start
- [x] add a task 'solo:destroy' that will run network destroy with the delete pvcs and secret flags, and uninstall the cluster setup as well
- [x] add a task 'solo:mirror-node' that will install the mirror node and mirror node explorer
- [x] add a task 'solo:destroy-mirror-node' that will uninstall the mirror node and the mirror node explorer
- [x] add a task 'solo:relay' that will deploy the json rpc relay
- [x] add a task 'solo:destroy-relay' that will uninstall the json rpc relay
- [x] add a task 'solo:deploy:all' that will run 'solo:deploy', 'solo:relay', and 'solo:mirror-node' and then the mirror node and mirror node explorer
- [x] add a task 'solo:destroy:all' that will run 'solo:destroy-mirror-node', 'solo:destroy-relay',  and 'solo:destroy'
```
