### ISSUE TITLE
Implement a ContextCommand to connect to an existing deployment

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#588]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/solo/issues/754
- [ ] https://github.com/hashgraph/solo/issues/755
- [ ] https://github.com/hashgraph/solo/issues/913
- [ ] https://github.com/hashgraph/solo/issues/950
- [ ] https://github.com/hashgraph/solo/issues/951
```
