### ISSUE TITLE
Create a Local Config for storing configurations on the users machine

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#590]
```[tasklist]
### Tasks
- [ ] When `Base.ts` constructs a new instance, then the local config should be injected using InversifyJS with singleton scope
- [ ] When no existing local config is found in the file system, then a new one will be created with and written to the file system as YAML
- [ ] When the local config is written to the file system, then its name will be `~/.solo/local-config.yaml`
- [ ] When the local config is read from the file system, then it will be parsed first from YAML using `yaml` library (NOTE: use `yaml`, we will later sunset `js-yaml`, since `js-yaml` has been inactive for too long)
- [ ] When `npm run build` is ran it will also run a new `generate-schema` `package.json` script, then generate a 'local-config.json' schema file
- [ ] When the local config is read from the file system, given it has been parsed from YAML into JSON, then it will validate against the local-config.json schema
- [ ] When the local config is created, then it will prompt the user for their email address with a simple validation
- [ ] When prompted for an email address, given a valid email address, then it the local config will be persisted to the file system as YAML
- [ ] When prompted for an email address, given an invalid email address, then the value will be rejected and the user will be prompted again
```

Notes:
- add new libraries
```
npm install inversify class-validator class-transformer ajv typescript-json-schema reflect-metadata --save
```
- Enable decorator support in TypeScript: You need to enable experimental decorators in your tsconfig.json file:
```
{
  "compilerOptions": {
    "lib": ["es6"],
    "types": ["reflect-metadata"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```
- interfaces:
```
interface Deployment {
  name : string // the name of the deployment, will be used as the namespace, so it needs to be available in all targeted clusters
  clusters : string[] // the names of the cluster, provided during the configuration of the deployment, must be unique
}
type IsEmail<T> = T extends string ? T matches /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/ : never;

type EmailAddress = IsEmail<string>;

interface LocalConfig {
  userEmailAddress: EmailAddress
  currentDeploymentName : string
  deployments: Map<deploymentName: string, deployment: Deployment>   // The name is the same as the namespace
  // context refers to the "CURRENT NAME", and cluster refers to the CLUSTER leveraged in kubeConfig.currentContext
  clusterMappings: Map<cluster: string: context: string> // reverse mapping of cluster name to context name for RemoteConfig
  async write() : void
}
```
- use [class-validator](https://www.npmjs.com/package/class-validator) decorators on the implementation class members.
- create `<root>/src/inversify.config.ts` and configure, see [InversifyJS documentation](https://github.com/inversify/InversifyJS?tab=readme-ov-file), we want local config to be a singleton
- add a new package.json script `generate-schema` and make `build` call it before it transpiles the TypeScript files
```
"scripts": {
    "generate-schema": "typescript-json-schema tsconfig.json LocalConfigFile --out local-config.json"
}
```
- validate the local config file against the generated schema using AJV as part of the constructor loading from Yaml process

NOTE: 
- for more details see this ChatGPT dialog: https://chatgpt.com/share/6704f2c1-c48c-8006-820a-f5f9a3df2b66
- more notes can be found in original design GH Issue: https://github.com/hashgraph/solo/issues/656
