### ISSUE TITLE
Change codebase to TypeScript

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#655]
In order to switch to a more object oriented codebase and better leverage dependency injection using abstracts we have decided to change Solo to a TypeScript codebase.
```[tasklist]
### Tasks
- [ ] Change all files to use the `*.ts` TypeScript file extension
- [ ] Update eslint for working with TypeScript code
- [ ] Update build process to add TypeScript compiler (5.6.2)
- [ ] Provide some form of documentation to existing developers to reduce learning curve and setup time, e.g. IntelliJ setup instructions, any changes in how to debug with IntelliJ, etc.
- [ ] Set strict: false in the tsconfig.json for starting us with minimal code changes
```
