### ISSUE TITLE
Create design for LocalConfig

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#656]
Create design for LocalConfig

```[tasklist]
### Tasks
- [x] mapping deployment clusters to contexts
- [x] injection using Inversify
- [x] TypeScript class
- [x] Serialize/deserialize to/from YAML/JSON/Class Instance
- [x] each cluster and its context will be stored in a map with the cluster reference as the key, to be used when working with K8 methods
```
required by: https://github.com/hashgraph/solo/issues/590

**Comment by jeromy-cannon** [comment]
```
❯ kubectl config get-contexts
CURRENT   NAME             CLUSTER                                                 AUTHINFO                                                NAMESPACE
          docker           docker-desktop                                          docker-desktop
          docker-desktop   docker-desktop                                          docker-desktop
          gke-edge         gke_hedera-automation_us-central1_hedera-arc-edge       gke_hedera-automation_us-central1_hedera-arc-edge
          gke-fullstack    gke_hedera-automation_us-central1_fullstack-test-edge   gke_hedera-automation_us-central1_fullstack-test-edge
          gke-secure       gke_hedera-automation_us-central1_hedera-arc-secure     gke_hedera-automation_us-central1_hedera-arc-secure
*         kind-solo-e2e    kind-solo-e2e                                           kind-solo-e2e
          re-lat           k8s.pft.dal.lat.ope.eng.swirldslabs.io                  release-engineering
```

**Comment by jeromy-cannon** [comment]
```
interface Deployment {
  name : string
  clusterAliases : string[]
}

interface LocalConfig {
  deployments: Deployment[]
  contextMappings: Map<clusterAlias : string, localClusterName : string>
  // localClusterName refers to the "CURRENT NAME" leveraged in kubeConfig.currentContext
}

**Comment by jeromy-cannon** [comment]
implementation story has been updated
