### ISSUE TITLE
Account key support

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#667]
```[tasklist]
### Tasks
- [x] Update `solo account create` to rename `--private-key` to `--ed25519-private-key`
- [x] Update the `solo account create` command description from: `Creates a new account with a new key and stores the key in the Kubernetes secrets` to: `Creates a new account with a new key and stores the key in the Kubernetes secrets, if you supply no key one will be generated for you, otherwise you may supply either a ECDSA or ED25519 private key`
- [x] Update `solo account update` to rename `--private-key` to `--ed25519-private-key`
- [x] Update `solo account update` to add support for `--ecdsa-private-key`
- [x] Update `solo account update` command description from: `Updates an existing account with the provided info` to `Updates an existing account with the provided info, if you want to update the private key, you can supply either ECDSA or ED25519 but not both`
- [ ] ensure flags, prompts, and test cases are also updated/covered appropriately
```
