### ISSUE TITLE
Remove ConfigManager caching capabilities to improve user experience

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#676]
While the caching of the ConfigManager reduces the number of flags that a user has to enter, it also causes a lot of confusion and sometimes doesn't automatically get uncached.  Considering our future designs with multi-cluster the caching of these flags needs to be removed.  We want the user to either use the prompts or the flags for each command, and the number of commands will be reduced in the future.

Here is a list, although there might be need to be more items that aren't documented:

```[tasklist]
### Tasks
- [x] update: `ConfigManager.constructor`, remove 2nd parameter `cachedConfigFile`
- [x] update: `ConfigManager.applyPrecedence` jsdoc refers to cached config
- [x] update: `ConfigManager.update`, remove 2nd parameter `persist`
- [x] update: `ConfigManager.persist`
- [x] remove: `ConfigManager.load`
- [x] remove: `constants.SOLO_CONFIG_FILE`
- [ ] many test cases will need updating and refactoring since they rely upon caching of the flags
- [ ] the workflow that generates the README will need to be updated
- [ ] the README template file may also need to be updated
```
