### ISSUE TITLE
Implement `solo context connect` part 1 of 2 - updates the LocalConfig by connecting a deployment to a k8s context

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#754]
- `solo context connect --context kind-solo --cluster kind --namespace solo-1`
  -  The context connect subcommand connects to a deployment and pulls back the RemoteConfig and ensures the kube. config has contexts created for all of the clusters in the RemoteConfig and that the RemoteConfig in those clusters are in sync.  
  - `--context kind-solo` - the CONTEXT_NAME  for `kubectl config use-context CONTEXT_NAME`
  - `--cluster kind-solo` - the CLUSTER as seen from running `kubectl config get-contexts`
  - `--namespace solo-1` - if the namespace is provided it will be used to update or create a deployment in the LocalConfig assigning the cluster provided

```[tasklist]
### Tasks
- [ ] When `solo context connect --quiet ` is invoked, then `contextName` will default to the current k8s context
- [ ] When `solo context connect` is invoked, the user will be prompted to supply a `contextName`, will default to the current k8s context, and supply a list for the user to choose from based on the values in their kube config
- [ ] When `solo context connect --quiet` is invoked, then `clusterName` will default to the clusterName of the cluster connected when connecting to the current k8s context
- [ ] When `solo context connect` is invoked, the user will be prompted to supply a `clusterName`
- [ ] When `solo context connect --quiet` is invoked, then `namespace` will default to the current k8s default namespace
- [ ] When `solo context connect` is invoked, the user will be prompted to supply a `namespace`, it will default to the current k8s default namespace
- [ ] When `solo context connect --context <context-name>` is invoked, then `contextName` will be set to the <context-name> passed in by the user
- [ ] When `solo context connect --cluster <cluster-name>` is invoked, then `clusterName` will be set to the <cluster-name> passed in by the user
- [ ] When `solo context connect --namespace <namespace>` is invoked, then `namespace` will be set to the <namespace> passed in by the user
- [ ] When `solo context connect` is invoked, then the deployment will be retrieved from the LocalConfig deployments Map using the namespace and a Deployment is returned then set the LocalConfig currentDeploymentName to the namespace
- [ ] When `solo context connect` is invoked, then the deployment will be retrieved from the LocalConfig deployments Map using the namespace and null is returned then do not set the LocalConfig currentDeploymentName
- [ ] When any changes are made to LocalConfig, then the changes will be persisted to the file system
```

- [ ] depends on #590
