### ISSUE TITLE
Create instructions on how to create expose ports necessary to create an SDK connection to both the Consenus Nodes plus the Mirror Node

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#816]
```[tasklist]
### Tasks
- [ ] Create a `docs/content/User/SDK.md`
- [ ] Add a 'SDK Usage' + ref: "/User/SDK.md" element in `docs/data/menu/main.yml`
- [ ] Reference instructions on [how to create a client node](https://docs.hedera.com/hedera/tutorials/consensus/submit-your-first-message) and fill out the consensus node network manually, similar to how we do in [solo using Client.fromConfig()](https://github.com/hashgraph/solo/blob/537398caf6cdcbce762ad6b6e5ae28a47dff860b/src/core/account_manager.ts#L240-L240)
- [ ] it looks like the mirror node can also be configured inside there: https://github.com/hashgraph/hedera-sdk-js/blob/ac4914112cb80deadd12ac350e19e27b06d43bf1/src/client/Client.js#L54-L54, or alternatively use nodeClient.setMirrorNetwork()
- [ ] we should add a test case to verify that it works correctly
- [ ] we need to ensure that we are providing the steps to expose the port forwards for both the consenus nodes as well as the mirror node network
```

**Comment by JeffreyDallas** [comment]
setMirrorNetwork shown as not implemented yet

https://github.com/hashgraph/hedera-sdk-js/blob/e44cdf846c99107976d07bc1d7b4476a060aacff/src/client/Client.js#L240
https://github.com/hashgraph/hedera-sdk-js/blob/e44cdf846c99107976d07bc1d7b4476a060aacff/src/client/Client.js#L735

**Comment by leninmehedy** [comment]
@JeffreyDallas and @jeromy-cannon I was thinking of the outline below where someone would be able to setup a network, accounts and use a code example to test it. We could use it for a technical workshop.

### Table of contents:

- Setup a network using solo
- Create account using solo
- Top-up account (e.g. with 10000 HBAR) using solo
- Retrieve account keys (DER encoded private key)
    (use kubectl command to retrieve from secrets unless solo allows to retrieve it)
- Create your .env File with MY_ACCOUNT_ID and MY_PRIVATE_KEY (DER encoded private key)
- Expose consensus node port (50211) to different ports using kubectl
```
  # for example, please test and update as required
   kubectl port-forward svc/haproxy-node0-svc -n solo 50211:30311 &
   kubectl port-forward svc/haproxy-node1-svc -n solo 50211:30411 &
   kubectl port-forward svc/haproxy-node2-svc -n solo 50211:30511 &
```
- Create a SDK client and query ledger
  (We need to provide a working code that uses SDK and the solo provisioned network. Existing doc provides example of using testnet, but people should be using a local network for testing)
  - prepare network object which is a map of: `host:port`: `accountId` 
  ```
  {
    "127.0.0.1:30311": "0.0.3"
    "127.0.0.1:30411": "0.0.4"
    "127.0.0.1:30511": "0.0.5"
  }
  ```
  - Use: `Client.fromConfig({ network: network, scheduleNetworkUpdate: false })`
  - Query the account balance

**Comment by jeromy-cannon** [comment]
@leninmehedy , yes, this is similar to what I was thinking as well.  We have an example folder already created as well.
