### ISSUE TITLE
Split current Readme into multiple pages and restructure docs

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#914]
- [x] Update the Hugo docs and readme/*.md files to match the structure and notes listed in "Docs navigation structure below"
- [x] remove Java column from Readme Requirements table
- [x] `solo --help` update the order listed to match closer to the order you would run them
- [x] `solo --help` lists `context` twice, update to only list it once
- [x] update to not need task and use npm install instructions in: https://hashgraph.github.io/solo/User/SDK/, also why do you need to clone sdk repo?
- [x] update based on latest: Docs/Development: https://hashgraph.github.io/solo/Developer/DEV/
- [ ] bonus: read in the subcommands from the `solo <command> --help` then iterate to get their output to use for the templates

- Docs navigation structure:
	- Getting Started -> Readme, NOTE: each item below are sections within the Readme.md, also remove table of contents, and note that other sections have moved to their own pages
		- description
		- full documentation link
		- requirements / version chart
		- setup
		- install solo
		- setup k8s
		- quick start (previously "Setup Kubernetes cluster")( after the remote cluster and local cluster then provide the commands only to stand up a network with mirror node and json rpc relay, link them to the "Deploy a standalone test network" page, make this static, the dynamic part will move to another page)
		- support
		- contributing
		- code of conduct
		- licensing
	- Solo CLI -> an overview of the CLI tool, plus dynamic: `solo --help`, NOTE: each item below is a unique page
		- Init -> heading + dynamic `solo init --help`
		- Context -> heading, table of contents, + dynamic `solo context --help`, `solo context connect --help`
		- Deployment
		- Cluster -> heading, table of contents, + dynamic `solo cluster --help`, `solo cluster list --help`, `solo cluster info --help`, `solo cluster setup --help`, `solo cluster reset --help`
		- Network -> heading, table of contents, + dynamic `solo network --help`, `solo network deploy --help`, `solo network destroy --help`, `solo network refresh --help`
		- Node -> heading, table of contents, + dynamic `solo node --help`, go through each one.. there are a lot.
		- Mirror Node -> heading, table of contents, + dynamic `solo mirror-node --help`, `solo mirror-node deploy --help`, `solo mirror-node destroy --help`
		- Relay -> heading, table of contents, + dynamic `solo relay --help`, `solo relay deploy --help`, `solo relay destroy --help`
		- Account -> heading, table of contents, + dynamic `solo account --help`, `solo account init --help`, `solo account create --help`, `solo account update --help`, `solo account get --help`
	- Usage, NOTE: each item below is a unique page
		- Deploy a standalone test network (use section from current readme)
		- Access Hedera Network services (use section from current readme)
		- Logs (use section from current readme)
		- For Developers Working on Hedera Service Repo (use section from current readme)
		- For Developers Working on Platform core (use section from current readme)
		- Using IntelliJ remote debug with Solo (use section from current readme)
		- Instructions for using Solo with Hedera JavaScript SDK (existing)
		- Running latest with clone of repo and Taskfile (new)
		- Hardware Requirements (new) (3 nodes, mirror node, and relay: RAM >= 8GB + CPU >= 4 for cluster, maybe show screenshot using Docker Desktop like we use with these settings) (would be good to know what it requires to run just a single node network without mirror node or relay (minimum))
		- How to use Mirror Node (new) (Torfinn and Tim Schmidt would be good people to run this by or get input from)
		- Environment Variables (new) (document the environment variables exposed in constants.ts)
	- Contributing
	- Frequently Asked Questions, NOTE: each item below are sections within the FAQ
		- Differences between Solo and Local Node, TBD, ask Torfinn, he is working on something
		- Q: How can I avoid using genesis keys? A: `solo account init` to be ran anytime after `solo node start`
		- Q: Where can I find the default account keys? A: it is the genesis key well documented, (link it or paste it here)
		- Q: How do I get the key for an account?  A: (give command to run and example output)
	- TypesScript Doc
	- Related Projects
